name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows you to manually trigger the sync from the GitHub UI if needed

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push -f https://SOU61204:$HF_TOKEN@huggingface.co/spaces/SOU61204/music-key-analyser-backend main